sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3.5-5.8.0"
install: 
  - pip install tox-travis
  - pip install pytest-cov
script:
  - tox
  - pytest --cov=ajilog tests
after_success:
  - coveralls
